# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 300)
        MainWindow.setMinimumSize(QtCore.QSize(700, 300))
        MainWindow.setMaximumSize(QtCore.QSize(700, 300))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.votemenu_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.votemenu_label.setGeometry(QtCore.QRect(260, 10, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.votemenu_label.setFont(font)
        self.votemenu_label.setObjectName("votemenu_label")
        self.canidate1_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.canidate1_button.setGeometry(QtCore.QRect(80, 190, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.canidate1_button.setFont(font)
        self.canidate1_button.setObjectName("canidate1_button")
        self.canidate2_button = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.canidate2_button.setGeometry(QtCore.QRect(410, 200, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.canidate2_button.setFont(font)
        self.canidate2_button.setObjectName("canidate2_button")
        self.submit_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(280, 230, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.submit_button.setFont(font)
        self.submit_button.setObjectName("submit_button")
        self.instruction_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.instruction_label.setGeometry(QtCore.QRect(20, 60, 671, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.instruction_label.setFont(font)
        self.instruction_label.setObjectName("instruction_label")
        self.id_input = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.id_input.setGeometry(QtCore.QRect(260, 130, 161, 31))
        self.id_input.setText("")
        self.id_input.setObjectName("id_input")
        self.id_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.id_label.setGeometry(QtCore.QRect(230, 130, 21, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.id_label.setFont(font)
        self.id_label.setObjectName("id_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Vote Menu"))
        self.votemenu_label.setText(_translate("MainWindow", "Vote Menu"))
        self.canidate1_button.setText(_translate("MainWindow", "Canidate 1 - John"))
        self.canidate2_button.setText(_translate("MainWindow", "Canidate 2 - Jane"))
        self.submit_button.setText(_translate("MainWindow", "SUBMIT"))
        self.instruction_label.setText(_translate("MainWindow", "Please enter ID number, choose a canidate, and click submit to cast your vote!"))
        self.id_label.setText(_translate("MainWindow", "ID"))



